theme: minima
title: CHEER's PERSONAL WEBSITE~
author: Cheer Chang
email: cheer.eed09@nctu.edu.tw
description: > # this means to ignore newlines until "baseurl:"
  I'm Cheer from Taipei, Taiwan. Currently study Electrical and Computer Engineering in National Chiao Tung University.
  I sometimes get frustrated in programming but still love it.
  Just learnt C language in my first semester in college.

# social links
instagram_username: cheer.chang # DO NOT include the @ character, or else the build will fail!
github_username:  cheer-cutie # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
